version: '3.8'
services:
    database:
        image: postgres:latest
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: test
        ports:
            - "8081:5432"

